name: build

on:
  push:
    branches: [ master ]

jobs:
  build-x86:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: configure
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
        mkdir build-x86
        cd build-x86
        set CC=cl
        set CXX=cl
        cmake -GNinja -DCMAKE_BUILD_TYPE=Release ..
    - name: make
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
        cmake --build build-x86
    - name: dist
      shell: cmd
      run: |
        mkdir dist-x86
        copy build-x86\loader.exe dist-x86
        copy build-x86\loaderw.exe dist-x86
    - name: artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: loader-x86
        # Directory containing files to upload
        path: dist-x86
  build-amd64:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: configure
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        mkdir build-amd64
        cd build-amd64
        set CC=cl
        set CXX=cl
        cmake -GNinja -DCMAKE_BUILD_TYPE=Release ..
    - name: make
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        cmake --build build-amd64
    - name: dist
      shell: cmd
      run: |
        mkdir dist-amd64
        copy build-amd64\loader.exe dist-amd64
        copy build-amd64\loaderw.exe dist-amd64
    - name: artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: loader-amd64
        # Directory containing files to upload
        path: dist-amd64
  build-aarch64:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: configure
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsamd64_arm64.bat"
        mkdir build-aarch64
        cd build-aarch64
        set CC=cl
        set CXX=cl
        cmake -GNinja -DCMAKE_BUILD_TYPE=Release ..
    - name: make
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        cmake --build build-aarch64
    - name: dist
      shell: cmd
      run: |
        mkdir dist-aarch64
        copy build-aarch64\loader.exe dist-aarch64
        copy build-aarch64\loaderw.exe dist-aarch64
    - name: artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: loader-aarch64
        # Directory containing files to upload
        path: dist-aarch64
